<?php

namespace System;

use Core\Bootstrap;
use Core\Component;
use Core\Hook;

class Alias extends Component {
  protected $aliases = [];

  /**
   * Sets up aliases.
   */
  function __construct() {
    $this->aliases = [
      'location' => [
        'package' => 'Core',
        'component' => 'Component',
        'method' => 'location',
        'custom_code' => <<<EOS
return call_user_func_array(['\\Core\\Component', 'location'], func_get_args());
EOS
      ],
      'extenders' => [
        'package' => 'Core',
        'component' => 'Component',
        'method' => 'extenders',
        'custom_code' => <<<EOS
return call_user_func_array(['\\Core\\Component', 'extenders'], func_get_args());
EOS
      ],
      'implementers' => [
        'package' => 'Core',
        'component' => 'Hook',
        'method' => 'implementers',
        'custom_code' => <<<EOS
return call_user_func_array(['\\Core\\Hook', 'implementers'], func_get_args());
EOS
      ],
    ];

    foreach (Hook::implementers('System\\Alias', 'Aliases', TRUE) as $implementer) {
      /* @var Alias\Aliases $implementer */
      $this->aliases = array_merge($this->aliases, $implementer::register());
    }

    foreach ($this->aliases as $function_name => $data) {
      if (function_exists($function_name))
        continue;

      $code = isset($data['custom_code']) ? $data['custom_code'] : <<<EOS
\$instance = {$data['package']}\\{$data['component']}::i();
return call_user_func_array([\$instance, '{$data['method']}'], func_get_args());
EOS;

      eval('function '.$function_name.'() {'.$code.'}');
    }

    $this->generateStubFile();
  }

  /**
   * Generate a dummy file with the function definitions for the aliases.
   */
  function generateStubFile() {
    $filename = 'cache'
      .DIRECTORY_SEPARATOR.'aliases.php';

    if (!Bootstrap::isDevelopmentMode() && file_exists($filename))
      return;

    $code = <<<EOS
<?php

/**
 * @file Alias stubs.
 * Generated by the System\Alias component.
 * This file doesn't actually get executed. It's generated automatically by the
 * component to get a list of the aliases, and for the auto-completion feature
 * in code editors to work.
 */

EOS;

    foreach ($this->aliases as $function_name => $data) {
      $reflection = new \ReflectionMethod("{$data['package']}\\{$data['component']}", $data['method']);
      $phpdoc = $reflection->getDocComment();
      if ($phpdoc)
        $phpdoc = PHP_EOL . $phpdoc;

      $params = [];
      foreach ($reflection->getParameters() as $param) {
        $params[] = '$' . $param->getName();
//        if ($param->isDefaultValueAvailable()) var_dump($param->getDefaultValue());
//        if ($param->isDefaultValueConstant()) var_dump($param->getDefaultValueConstantName());
      }
      $params = implode(', ', $params);

      $code .= <<<EOS
$phpdoc
function $function_name($params) {
}

EOS;
    }

    file_put_contents($filename, $code);
  }

}
